scrape_configs:
  - job_name: 'Spring Boot Application'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['docker.for.mac.localhost:6000']
        labels:
          application: 'Dashboard Application'